 base:
   project: winequality
   random_state: 42
   target_col: TARGET
 data_source:
   s3_source: E:/simple_app/data_given/winequality.csv
 load_data:
   raw_dataset_csv: E:/simple_app/data/raw/winequality.csv
 split_data:
   train_path: E:/simple_app/data/processed/train_winequality.csv
   test_path: E:/simple_app/data/processed/test_winequality.csv
   test_size: 0.2
 estimators:
   ElasticNet:
     params:
       alpha: 0.9
       l1_ratio: 0.4
 model_dir: E:/simple_app/Saved_models
 reports:
   scores: E:/simple_app/reports/scores.json
   params: E:/simple_app/reports/params.json
